dist: trusty
sudo: false
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-ttf-dev

script:
    - CXX=/usr/bin/g++-5
    - CC=/usr/bin/gcc-5
    - ./build_google_mock.sh
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4
    - ctest
