dist: trusty
sudo: false
language: cpp

addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
            - g++-7
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-ttf-dev

script:
    - CXX=/usr/bin/g++-7
    - CC=/usr/bin/gcc-7
    - ./build_google_mock.sh
    - mkdir build
    - cd build
    - ln -s ../assets assets
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4
    - ctest
